config/routes.rb
Rails.application.routes.draw do
  get "comments/index"
  get "follows/index"
  devise_for :users
  get "search/index"
  get "search" => "search#index"
  # custom routes for follow
  post "/users/:id/follow", to: "users#follow", as: "follow_user"
  post "/users/:id/unfollow", to: "users#unfollow", as: "unfollow_user"
  # custom routes for like
  post "/posts/:id/like", to: "posts#like", as: "like_posts"
  post "/posts/:id/dislike", to: "posts#dislike", as: "dislike_posts"
  # custom routes for comments
  post "/posts/:id/comment", to: "posts#createcomment", as: "create_comment"
  post "posts/:id/comments/:comment_id/delete", to: "posts#deletecomment", as: "delete_comment"
  get "home/index"
  get "home/show"
  root to: "home#index"
  post "uploads", to: "uploads#create"
  resources :users, only: [ :show, :edit, :update ] do
    # nested rote for the follows to have the user id
    get "follows", to: "follows#index"
  end
  resources :posts, only: [ :new, :create, :show, :destroy, :index ] do
    post :update_time, on: :collection
    resources :comments, only: [ :create ] do
      post "reply", on: :member  # POST /comments/:id/reply
    end
  end
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/post.rb
class Post < ApplicationRecord
  after_commit :create_hash_tags, on: :create

  belongs_to :user
  has_one_attached :image
  validate :image_presence
  has_many :post_hash_tags
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :hash_tags, through: :post_hash_tags

  def create_hash_tags
    extract_name_hash_tags.each do |name|
      hash_tags.create(name: name)
    end
  end

  def extract_name_hash_tags
    description.to_s.scan(/#\w+/).map { |name| name.gsub("#", "") }
  end

  private

  def image_presence
    errors.add(:image, "can't be blank") unless image.attached?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :setpost, only: [ :show, :like, :dislike, :createcomment ]

  def create
    @post = Post.new(post_params)

    if params[:post][:image].present?
      @post.image.attach(params[:post][:image])
    end

    if @post.save
      redirect_to root_path, notice: "Post created successfully"
    else
      redirect_to root_path, alert: "Post creation failed"
    end
  end

  def show
  end

  def new
      @post = Post.new

      if request.xhr?
        render layout: false
      end
  end

  def update_time
    @posts = Post.all

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("posts_list", partial: "posts/posts", locals: { posts: @posts })
      end
      format.html { redirect_to posts_path } # fallback
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to user_path(current_user),  notice: "Post deleted successfully"
  end

  def like
    like = Like.new(user: current_user, post: @post)

    if like.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_back fallback_location: root_path }
      end
    else
      flash[:alert] = "Your like did not work"
      redirect_back fallback_location: root_path
    end
  end

  def dislike
    current_user.likes.find_by(post: @post)&.destroy

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_back fallback_location: root_path }
    end
  end

  def createcomment
    @comment = Comment.new(
      user: current_user,
      post: @post,
      content: params[:content],
      parent_id: params[:parent_id]
    )

    if @comment.save
      Rails.logger.debug ">>>>>> Format: #{request.format}"
      puts "--------------------------------------------------------------------------------------------#{request.format}"
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_back fallback_location: root_path, notice: "Comment added successfully" }
      end
    else
      Rails.logger.debug ">>>>>> Format: #{request.format}"
      respond_to do |format|
        format.html { redirect_back fallback_location: root_path, alert: "Failed to add comment" }
      end
    end
  end

  def deletecomment
    comment = current_user.comments.find_by(id: params[:comment_id], post_id: params[:id])
    comment&.destroy

    redirect_back fallback_location: root_path, notice: "COmment deleted successfully"
  end

  private

  def setpost
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:description, :user_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true, id: "post-upload-form" } do |f| %>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Upload Image</label>
    <div id="my-dropzone" class="dropzone"></div>

    <noscript>
      <%= f.file_field :image, class: "form-control" %>
    </noscript>
  </div>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="text-center mt-3">
    <%= f.submit "Create Post", class: "btn btn-success" %>
    <button type="button" onclick="closeModal()" class="btn btn-secondary">Cancel</button>
  </div>
<% end %>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    Dropzone.autoDiscover = false;

    $(document).on('click', '.open-post-modal', function(e) {
      e.preventDefault();
      const url = $(this).data('url');

      $('#modalOverlay').fadeIn();
      $('#dynamicModalForm').load(url, function() {
        $(this).fadeIn();

        // Now initialize Dropzone on the dynamically loaded form
        if (Dropzone.instances.length > 0) Dropzone.instances.forEach(dz => dz.destroy());

        new Dropzone("#post-upload-form", {
          paramName: "post[image]",
          maxFiles: 1,
          acceptedFiles: "image/*",
          addRemoveLinks: true,
          dictDefaultMessage: "Drag an image or click to upload"
        });
      });
    });

    // Optional: click outside to close modal
    $('#modalOverlay').on('click', closeModal);
  });

  function closeModal() {
    $('#dynamicModalForm').fadeOut();
    $('#modalOverlay').fadeOut();
  }
</script>

app/views/posts/index.html.erb
<%#u.likes.map(&:post)%>
<div id="turbo-test">
  <p>This is Turbo test block - <%= Time.current.strftime("%H:%M:%S") %></p>
</div>

<%= form_with url: update_time_posts_path, method: :post, data: { turbo_stream: true } do %>
  <%= submit_tag "Update Time" %>
<% end %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div style="height:80vh;display:flex;justify-content:center">
  <div class="post-show row" style="width:100vh;height:50vh;background-color:white">
    <div class="col-md-8">
      <%=image_tag @post.image, class: 'image' ,style:"height:100%"%>
    </div>
    <div class="col-md-4">
      <div class="user">
        <div class="avatar">
          <% if @post.user.avatar.attached? %>
            <%= link_to user_path(@post.user) do %>
              <%= image_tag @post.user.avatar %>
            <% end %>
          <% end %>
        </div>
        <%= link_to @post.user.username, user_path(@post.user), class: 'username' %>
      </div>
      <div class="description">
        <% @post.description.to_s.split(' ').each do |word| %>
                <% if word.start_with?('#') %>
                  <%= link_to word, search_path(query: word) %>
                <%else %>
                  <%= word %>
                <%end %>
        <% end %>
      </div>
      <div class="delete" style="display:flex;height:60%;justify-content:flex-end;align-items:flex-end">
          <% if current_user.posts.exists?(@post.id) %>
            <%= button_to 'Remove', post_path(@post),class:"btn btn-primary", method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/update_time.turbo_stream.erb
<%= turbo_stream.replace "turbo-test" do %>
  <div id="turbo-test">
    <p>This is Turbo test block - <%= Time.current.strftime("%H:%M:%S") %></p>
  </div>
<% end %>